### ISSUE TITLE
VSTi Yamaha

### ISSUE THREAD

**Issue by Torinde** [johnnovak/Nuked-SC55-CLAP#3]
Is it possible for [Yamaha S-YXG50 Portable VSTi](https://veg.by/en/projects/syxg50/) to be implemented as CLAP plugin?

I don't see that mentioned at [Future applications](https://github.com/dosbox-staging/dosbox-staging/pull/4090), but maybe it has some advantages, for example against [bit-rot](https://github.com/joncampbell123/dosbox-x/issues/3632#issuecomment-1465441440)?

**Comment by johnnovak** [comment]
The x86 binary would need to be decomplied / reverse engineered, then it would need to be reimplemented in C++. I thought about it, but it probably a lot of work.

Agree on the bit-rot, an open-source reimplementation would be ideal.

So maybe... one day. But don't hold your breath.
